// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractMembershipDao is the data access object for the table kids_contract_membership.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractMembershipDao struct {
	*internal.KidsContractMembershipDao
}

var (
	// KidsContractMembership is a globally accessible object for table kids_contract_membership operations.
	KidsContractMembership = kidsContractMembershipDao{internal.NewKidsContractMembershipDao()}
)

// Add your custom methods and functionality below.
