// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractCircleSelectionDao is the data access object for the table kids_contract_circle_selection.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractCircleSelectionDao struct {
	*internal.KidsContractCircleSelectionDao
}

var (
	// KidsContractCircleSelection is a globally accessible object for table kids_contract_circle_selection operations.
	KidsContractCircleSelection = kidsContractCircleSelectionDao{internal.NewKidsContractCircleSelectionDao()}
)

// Add your custom methods and functionality below.
