// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsTaskPresetDao is the data access object for the table kids_task_preset.
// You can define custom methods on it to extend its functionality as needed.
type kidsTaskPresetDao struct {
	*internal.KidsTaskPresetDao
}

var (
	// KidsTaskPreset is a globally accessible object for table kids_task_preset operations.
	KidsTaskPreset = kidsTaskPresetDao{internal.NewKidsTaskPresetDao()}
)

// Add your custom methods and functionality below.
