// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsStarRecordDao is the data access object for the table kids_star_record.
// You can define custom methods on it to extend its functionality as needed.
type kidsStarRecordDao struct {
	*internal.KidsStarRecordDao
}

var (
	// KidsStarRecord is a globally accessible object for table kids_star_record operations.
	KidsStarRecord = kidsStarRecordDao{internal.NewKidsStarRecordDao()}
)

// Add your custom methods and functionality below.
