// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsTaskDao is the data access object for the table kids_task.
// You can define custom methods on it to extend its functionality as needed.
type kidsTaskDao struct {
	*internal.KidsTaskDao
}

var (
	// KidsTask is a globally accessible object for table kids_task operations.
	KidsTask = kidsTaskDao{internal.NewKidsTaskDao()}
)

// Add your custom methods and functionality below.
