// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractAccountBindingDao is the data access object for the table kids_contract_account_binding.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractAccountBindingDao struct {
	*internal.KidsContractAccountBindingDao
}

var (
	// KidsContractAccountBinding is a globally accessible object for table kids_contract_account_binding operations.
	KidsContractAccountBinding = kidsContractAccountBindingDao{internal.NewKidsContractAccountBindingDao()}
)

// Add your custom methods and functionality below.
