// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsRewardCooldownDao is the data access object for the table kids_reward_cooldown.
// You can define custom methods on it to extend its functionality as needed.
type kidsRewardCooldownDao struct {
	*internal.KidsRewardCooldownDao
}

var (
	// KidsRewardCooldown is a globally accessible object for table kids_reward_cooldown operations.
	KidsRewardCooldown = kidsRewardCooldownDao{internal.NewKidsRewardCooldownDao()}
)

// Add your custom methods and functionality below.
