// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsCircleDao is the data access object for the table kids_circle.
// You can define custom methods on it to extend its functionality as needed.
type kidsCircleDao struct {
	*internal.KidsCircleDao
}

var (
	// KidsCircle is a globally accessible object for table kids_circle operations.
	KidsCircle = kidsCircleDao{internal.NewKidsCircleDao()}
)

// Add your custom methods and functionality below.
