// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractTaskDao is the data access object for the table kids_contract_task.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractTaskDao struct {
	*internal.KidsContractTaskDao
}

var (
	// KidsContractTask is a globally accessible object for table kids_contract_task operations.
	KidsContractTask = kidsContractTaskDao{internal.NewKidsContractTaskDao()}
)

// Add your custom methods and functionality below.
