// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsTaskAssignmentDao is the data access object for the table kids_task_assignment.
// You can define custom methods on it to extend its functionality as needed.
type kidsTaskAssignmentDao struct {
	*internal.KidsTaskAssignmentDao
}

var (
	// KidsTaskAssignment is a globally accessible object for table kids_task_assignment operations.
	KidsTaskAssignment = kidsTaskAssignmentDao{internal.NewKidsTaskAssignmentDao()}
)

// Add your custom methods and functionality below.
