// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsRewardRedeemRecordDao is the data access object for the table kids_reward_redeem_record.
// You can define custom methods on it to extend its functionality as needed.
type kidsRewardRedeemRecordDao struct {
	*internal.KidsRewardRedeemRecordDao
}

var (
	// KidsRewardRedeemRecord is a globally accessible object for table kids_reward_redeem_record operations.
	KidsRewardRedeemRecord = kidsRewardRedeemRecordDao{internal.NewKidsRewardRedeemRecordDao()}
)

// Add your custom methods and functionality below.
