// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsFamilyMemberDao is the data access object for the table kids_family_member.
// You can define custom methods on it to extend its functionality as needed.
type kidsFamilyMemberDao struct {
	*internal.KidsFamilyMemberDao
}

var (
	// KidsFamilyMember is a globally accessible object for table kids_family_member operations.
	KidsFamilyMember = kidsFamilyMemberDao{internal.NewKidsFamilyMemberDao()}
)

// Add your custom methods and functionality below.
