// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractInviteDao is the data access object for the table kids_contract_invite.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractInviteDao struct {
	*internal.KidsContractInviteDao
}

var (
	// KidsContractInvite is a globally accessible object for table kids_contract_invite operations.
	KidsContractInvite = kidsContractInviteDao{internal.NewKidsContractInviteDao()}
)

// Add your custom methods and functionality below.
