// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsMutationReceiptDao is the data access object for the table kids_mutation_receipt.
// You can define custom methods on it to extend its functionality as needed.
type kidsMutationReceiptDao struct {
	*internal.KidsMutationReceiptDao
}

var (
	// KidsMutationReceipt is a globally accessible object for table kids_mutation_receipt operations.
	KidsMutationReceipt = kidsMutationReceiptDao{internal.NewKidsMutationReceiptDao()}
)

// Add your custom methods and functionality below.
