// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractSessionDao is the data access object for the table kids_contract_session.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractSessionDao struct {
	*internal.KidsContractSessionDao
}

var (
	// KidsContractSession is a globally accessible object for table kids_contract_session operations.
	KidsContractSession = kidsContractSessionDao{internal.NewKidsContractSessionDao()}
)

// Add your custom methods and functionality below.
