// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsIdentitySessionDao is the data access object for the table kids_identity_session.
// You can define custom methods on it to extend its functionality as needed.
type kidsIdentitySessionDao struct {
	*internal.KidsIdentitySessionDao
}

var (
	// KidsIdentitySession is a globally accessible object for table kids_identity_session operations.
	KidsIdentitySession = kidsIdentitySessionDao{internal.NewKidsIdentitySessionDao()}
)

// Add your custom methods and functionality below.
