// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsStarLedgerDao is the data access object for the table kids_star_ledger.
// You can define custom methods on it to extend its functionality as needed.
type kidsStarLedgerDao struct {
	*internal.KidsStarLedgerDao
}

var (
	// KidsStarLedger is a globally accessible object for table kids_star_ledger operations.
	KidsStarLedger = kidsStarLedgerDao{internal.NewKidsStarLedgerDao()}
)

// Add your custom methods and functionality below.
