// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractMemberDao is the data access object for the table kids_contract_member.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractMemberDao struct {
	*internal.KidsContractMemberDao
}

var (
	// KidsContractMember is a globally accessible object for table kids_contract_member operations.
	KidsContractMember = kidsContractMemberDao{internal.NewKidsContractMemberDao()}
)

// Add your custom methods and functionality below.
