// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsRequestDeduplicationDao is the data access object for the table kids_request_deduplication.
// You can define custom methods on it to extend its functionality as needed.
type kidsRequestDeduplicationDao struct {
	*internal.KidsRequestDeduplicationDao
}

var (
	// KidsRequestDeduplication is a globally accessible object for table kids_request_deduplication operations.
	KidsRequestDeduplication = kidsRequestDeduplicationDao{internal.NewKidsRequestDeduplicationDao()}
)

// Add your custom methods and functionality below.
