// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsTaskDefinitionDao is the data access object for the table kids_task_definition.
// You can define custom methods on it to extend its functionality as needed.
type kidsTaskDefinitionDao struct {
	*internal.KidsTaskDefinitionDao
}

var (
	// KidsTaskDefinition is a globally accessible object for table kids_task_definition operations.
	KidsTaskDefinition = kidsTaskDefinitionDao{internal.NewKidsTaskDefinitionDao()}
)

// Add your custom methods and functionality below.
