// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsRewardDao is the data access object for the table kids_reward.
// You can define custom methods on it to extend its functionality as needed.
type kidsRewardDao struct {
	*internal.KidsRewardDao
}

var (
	// KidsReward is a globally accessible object for table kids_reward operations.
	KidsReward = kidsRewardDao{internal.NewKidsRewardDao()}
)

// Add your custom methods and functionality below.
