// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractReceiptDao is the data access object for the table kids_contract_receipt.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractReceiptDao struct {
	*internal.KidsContractReceiptDao
}

var (
	// KidsContractReceipt is a globally accessible object for table kids_contract_receipt operations.
	KidsContractReceipt = kidsContractReceiptDao{internal.NewKidsContractReceiptDao()}
)

// Add your custom methods and functionality below.
