// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsRewardExchangeDao is the data access object for the table kids_reward_exchange.
// You can define custom methods on it to extend its functionality as needed.
type kidsRewardExchangeDao struct {
	*internal.KidsRewardExchangeDao
}

var (
	// KidsRewardExchange is a globally accessible object for table kids_reward_exchange operations.
	KidsRewardExchange = kidsRewardExchangeDao{internal.NewKidsRewardExchangeDao()}
)

// Add your custom methods and functionality below.
