// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsCircleMembershipDao is the data access object for the table kids_circle_membership.
// You can define custom methods on it to extend its functionality as needed.
type kidsCircleMembershipDao struct {
	*internal.KidsCircleMembershipDao
}

var (
	// KidsCircleMembership is a globally accessible object for table kids_circle_membership operations.
	KidsCircleMembership = kidsCircleMembershipDao{internal.NewKidsCircleMembershipDao()}
)

// Add your custom methods and functionality below.
