// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsTaskCancellationDao is the data access object for the table kids_task_cancellation.
// You can define custom methods on it to extend its functionality as needed.
type kidsTaskCancellationDao struct {
	*internal.KidsTaskCancellationDao
}

var (
	// KidsTaskCancellation is a globally accessible object for table kids_task_cancellation operations.
	KidsTaskCancellation = kidsTaskCancellationDao{internal.NewKidsTaskCancellationDao()}
)

// Add your custom methods and functionality below.
