// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractTaskAssignmentDao is the data access object for the table kids_contract_task_assignment.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractTaskAssignmentDao struct {
	*internal.KidsContractTaskAssignmentDao
}

var (
	// KidsContractTaskAssignment is a globally accessible object for table kids_contract_task_assignment operations.
	KidsContractTaskAssignment = kidsContractTaskAssignmentDao{internal.NewKidsContractTaskAssignmentDao()}
)

// Add your custom methods and functionality below.
