// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsNotificationDao is the data access object for the table kids_notification.
// You can define custom methods on it to extend its functionality as needed.
type kidsNotificationDao struct {
	*internal.KidsNotificationDao
}

var (
	// KidsNotification is a globally accessible object for table kids_notification operations.
	KidsNotification = kidsNotificationDao{internal.NewKidsNotificationDao()}
)

// Add your custom methods and functionality below.
