// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsCircleUserDao is the data access object for the table kids_circle_user.
// You can define custom methods on it to extend its functionality as needed.
type kidsCircleUserDao struct {
	*internal.KidsCircleUserDao
}

var (
	// KidsCircleUser is a globally accessible object for table kids_circle_user operations.
	KidsCircleUser = kidsCircleUserDao{internal.NewKidsCircleUserDao()}
)

// Add your custom methods and functionality below.
