// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsUserAuthDao is the data access object for the table kids_user_auth.
// You can define custom methods on it to extend its functionality as needed.
type kidsUserAuthDao struct {
	*internal.KidsUserAuthDao
}

var (
	// KidsUserAuth is a globally accessible object for table kids_user_auth operations.
	KidsUserAuth = kidsUserAuthDao{internal.NewKidsUserAuthDao()}
)

// Add your custom methods and functionality below.
