// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsNotificationOutboxDao is the data access object for the table kids_notification_outbox.
// You can define custom methods on it to extend its functionality as needed.
type kidsNotificationOutboxDao struct {
	*internal.KidsNotificationOutboxDao
}

var (
	// KidsNotificationOutbox is a globally accessible object for table kids_notification_outbox operations.
	KidsNotificationOutbox = kidsNotificationOutboxDao{internal.NewKidsNotificationOutboxDao()}
)

// Add your custom methods and functionality below.
