// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsInviteCodeDao is the data access object for the table kids_invite_code.
// You can define custom methods on it to extend its functionality as needed.
type kidsInviteCodeDao struct {
	*internal.KidsInviteCodeDao
}

var (
	// KidsInviteCode is a globally accessible object for table kids_invite_code operations.
	KidsInviteCode = kidsInviteCodeDao{internal.NewKidsInviteCodeDao()}
)

// Add your custom methods and functionality below.
