// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractTaskOccurrenceDao is the data access object for the table kids_contract_task_occurrence.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractTaskOccurrenceDao struct {
	*internal.KidsContractTaskOccurrenceDao
}

var (
	// KidsContractTaskOccurrence is a globally accessible object for table kids_contract_task_occurrence operations.
	KidsContractTaskOccurrence = kidsContractTaskOccurrenceDao{internal.NewKidsContractTaskOccurrenceDao()}
)

// Add your custom methods and functionality below.
