// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsRewardAssigneeDao is the data access object for the table kids_reward_assignee.
// You can define custom methods on it to extend its functionality as needed.
type kidsRewardAssigneeDao struct {
	*internal.KidsRewardAssigneeDao
}

var (
	// KidsRewardAssignee is a globally accessible object for table kids_reward_assignee operations.
	KidsRewardAssignee = kidsRewardAssigneeDao{internal.NewKidsRewardAssigneeDao()}
)

// Add your custom methods and functionality below.
