// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsAssetDao is the data access object for the table kids_asset.
// You can define custom methods on it to extend its functionality as needed.
type kidsAssetDao struct {
	*internal.KidsAssetDao
}

var (
	// KidsAsset is a globally accessible object for table kids_asset operations.
	KidsAsset = kidsAssetDao{internal.NewKidsAssetDao()}
)

// Add your custom methods and functionality below.
