// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsStarBalanceDao is the data access object for the table kids_star_balance.
// You can define custom methods on it to extend its functionality as needed.
type kidsStarBalanceDao struct {
	*internal.KidsStarBalanceDao
}

var (
	// KidsStarBalance is a globally accessible object for table kids_star_balance operations.
	KidsStarBalance = kidsStarBalanceDao{internal.NewKidsStarBalanceDao()}
)

// Add your custom methods and functionality below.
