// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsUserTokenDao is the data access object for the table kids_user_token.
// You can define custom methods on it to extend its functionality as needed.
type kidsUserTokenDao struct {
	*internal.KidsUserTokenDao
}

var (
	// KidsUserToken is a globally accessible object for table kids_user_token operations.
	KidsUserToken = kidsUserTokenDao{internal.NewKidsUserTokenDao()}
)

// Add your custom methods and functionality below.
