// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsFeedbackDao is the data access object for the table kids_feedback.
// You can define custom methods on it to extend its functionality as needed.
type kidsFeedbackDao struct {
	*internal.KidsFeedbackDao
}

var (
	// KidsFeedback is a globally accessible object for table kids_feedback operations.
	KidsFeedback = kidsFeedbackDao{internal.NewKidsFeedbackDao()}
)

// Add your custom methods and functionality below.
