// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsAccountBindingDao is the data access object for the table kids_account_binding.
// You can define custom methods on it to extend its functionality as needed.
type kidsAccountBindingDao struct {
	*internal.KidsAccountBindingDao
}

var (
	// KidsAccountBinding is a globally accessible object for table kids_account_binding operations.
	KidsAccountBinding = kidsAccountBindingDao{internal.NewKidsAccountBindingDao()}
)

// Add your custom methods and functionality below.
