// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractBalanceDao is the data access object for the table kids_contract_balance.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractBalanceDao struct {
	*internal.KidsContractBalanceDao
}

var (
	// KidsContractBalance is a globally accessible object for table kids_contract_balance operations.
	KidsContractBalance = kidsContractBalanceDao{internal.NewKidsContractBalanceDao()}
)

// Add your custom methods and functionality below.
