// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsCircleInfoDao is the data access object for the table kids_circle_info.
// You can define custom methods on it to extend its functionality as needed.
type kidsCircleInfoDao struct {
	*internal.KidsCircleInfoDao
}

var (
	// KidsCircleInfo is a globally accessible object for table kids_circle_info operations.
	KidsCircleInfo = kidsCircleInfoDao{internal.NewKidsCircleInfoDao()}
)

// Add your custom methods and functionality below.
