// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsRewardPresetDao is the data access object for the table kids_reward_preset.
// You can define custom methods on it to extend its functionality as needed.
type kidsRewardPresetDao struct {
	*internal.KidsRewardPresetDao
}

var (
	// KidsRewardPreset is a globally accessible object for table kids_reward_preset operations.
	KidsRewardPreset = kidsRewardPresetDao{internal.NewKidsRewardPresetDao()}
)

// Add your custom methods and functionality below.
