// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractTaskTagDao is the data access object for the table kids_contract_task_tag.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractTaskTagDao struct {
	*internal.KidsContractTaskTagDao
}

var (
	// KidsContractTaskTag is a globally accessible object for table kids_contract_task_tag operations.
	KidsContractTaskTag = kidsContractTaskTagDao{internal.NewKidsContractTaskTagDao()}
)

// Add your custom methods and functionality below.
