// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsMemberDao is the data access object for the table kids_member.
// You can define custom methods on it to extend its functionality as needed.
type kidsMemberDao struct {
	*internal.KidsMemberDao
}

var (
	// KidsMember is a globally accessible object for table kids_member operations.
	KidsMember = kidsMemberDao{internal.NewKidsMemberDao()}
)

// Add your custom methods and functionality below.
