// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractAdministratorDao is the data access object for the table kids_contract_administrator.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractAdministratorDao struct {
	*internal.KidsContractAdministratorDao
}

var (
	// KidsContractAdministrator is a globally accessible object for table kids_contract_administrator operations.
	KidsContractAdministrator = kidsContractAdministratorDao{internal.NewKidsContractAdministratorDao()}
)

// Add your custom methods and functionality below.
