// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractSequenceDao is the data access object for the table kids_contract_sequence.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractSequenceDao struct {
	*internal.KidsContractSequenceDao
}

var (
	// KidsContractSequence is a globally accessible object for table kids_contract_sequence operations.
	KidsContractSequence = kidsContractSequenceDao{internal.NewKidsContractSequenceDao()}
)

// Add your custom methods and functionality below.
