// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractFeedbackDao is the data access object for the table kids_contract_feedback.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractFeedbackDao struct {
	*internal.KidsContractFeedbackDao
}

var (
	// KidsContractFeedback is a globally accessible object for table kids_contract_feedback operations.
	KidsContractFeedback = kidsContractFeedbackDao{internal.NewKidsContractFeedbackDao()}
)

// Add your custom methods and functionality below.
