// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsTaskTagDao is the data access object for the table kids_task_tag.
// You can define custom methods on it to extend its functionality as needed.
type kidsTaskTagDao struct {
	*internal.KidsTaskTagDao
}

var (
	// KidsTaskTag is a globally accessible object for table kids_task_tag operations.
	KidsTaskTag = kidsTaskTagDao{internal.NewKidsTaskTagDao()}
)

// Add your custom methods and functionality below.
