// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsInvitationDao is the data access object for the table kids_invitation.
// You can define custom methods on it to extend its functionality as needed.
type kidsInvitationDao struct {
	*internal.KidsInvitationDao
}

var (
	// KidsInvitation is a globally accessible object for table kids_invitation operations.
	KidsInvitation = kidsInvitationDao{internal.NewKidsInvitationDao()}
)

// Add your custom methods and functionality below.
