// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractAssetUploadDao is the data access object for the table kids_contract_asset_upload.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractAssetUploadDao struct {
	*internal.KidsContractAssetUploadDao
}

var (
	// KidsContractAssetUpload is a globally accessible object for table kids_contract_asset_upload operations.
	KidsContractAssetUpload = kidsContractAssetUploadDao{internal.NewKidsContractAssetUploadDao()}
)

// Add your custom methods and functionality below.
