// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsTaskCompletionDao is the data access object for the table kids_task_completion.
// You can define custom methods on it to extend its functionality as needed.
type kidsTaskCompletionDao struct {
	*internal.KidsTaskCompletionDao
}

var (
	// KidsTaskCompletion is a globally accessible object for table kids_task_completion operations.
	KidsTaskCompletion = kidsTaskCompletionDao{internal.NewKidsTaskCompletionDao()}
)

// Add your custom methods and functionality below.
