// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractIdempotencyDao is the data access object for the table kids_contract_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractIdempotencyDao struct {
	*internal.KidsContractIdempotencyDao
}

var (
	// KidsContractIdempotency is a globally accessible object for table kids_contract_idempotency operations.
	KidsContractIdempotency = kidsContractIdempotencyDao{internal.NewKidsContractIdempotencyDao()}
)

// Add your custom methods and functionality below.
