// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsTaskOccurrenceDao is the data access object for the table kids_task_occurrence.
// You can define custom methods on it to extend its functionality as needed.
type kidsTaskOccurrenceDao struct {
	*internal.KidsTaskOccurrenceDao
}

var (
	// KidsTaskOccurrence is a globally accessible object for table kids_task_occurrence operations.
	KidsTaskOccurrence = kidsTaskOccurrenceDao{internal.NewKidsTaskOccurrenceDao()}
)

// Add your custom methods and functionality below.
