// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsAssetUploadDao is the data access object for the table kids_asset_upload.
// You can define custom methods on it to extend its functionality as needed.
type kidsAssetUploadDao struct {
	*internal.KidsAssetUploadDao
}

var (
	// KidsAssetUpload is a globally accessible object for table kids_asset_upload operations.
	KidsAssetUpload = kidsAssetUploadDao{internal.NewKidsAssetUploadDao()}
)

// Add your custom methods and functionality below.
