// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractAssetDao is the data access object for the table kids_contract_asset.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractAssetDao struct {
	*internal.KidsContractAssetDao
}

var (
	// KidsContractAsset is a globally accessible object for table kids_contract_asset operations.
	KidsContractAsset = kidsContractAssetDao{internal.NewKidsContractAssetDao()}
)

// Add your custom methods and functionality below.
