// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractEntitlementDao is the data access object for the table kids_contract_entitlement.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractEntitlementDao struct {
	*internal.KidsContractEntitlementDao
}

var (
	// KidsContractEntitlement is a globally accessible object for table kids_contract_entitlement operations.
	KidsContractEntitlement = kidsContractEntitlementDao{internal.NewKidsContractEntitlementDao()}
)

// Add your custom methods and functionality below.
