// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsSyncSequenceDao is the data access object for the table kids_sync_sequence.
// You can define custom methods on it to extend its functionality as needed.
type kidsSyncSequenceDao struct {
	*internal.KidsSyncSequenceDao
}

var (
	// KidsSyncSequence is a globally accessible object for table kids_sync_sequence operations.
	KidsSyncSequence = kidsSyncSequenceDao{internal.NewKidsSyncSequenceDao()}
)

// Add your custom methods and functionality below.
