// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsTaskAssigneeDao is the data access object for the table kids_task_assignee.
// You can define custom methods on it to extend its functionality as needed.
type kidsTaskAssigneeDao struct {
	*internal.KidsTaskAssigneeDao
}

var (
	// KidsTaskAssignee is a globally accessible object for table kids_task_assignee operations.
	KidsTaskAssignee = kidsTaskAssigneeDao{internal.NewKidsTaskAssigneeDao()}
)

// Add your custom methods and functionality below.
