// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractAccountDao is the data access object for the table kids_contract_account.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractAccountDao struct {
	*internal.KidsContractAccountDao
}

var (
	// KidsContractAccount is a globally accessible object for table kids_contract_account operations.
	KidsContractAccount = kidsContractAccountDao{internal.NewKidsContractAccountDao()}
)

// Add your custom methods and functionality below.
