// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsEntitlementDao is the data access object for the table kids_entitlement.
// You can define custom methods on it to extend its functionality as needed.
type kidsEntitlementDao struct {
	*internal.KidsEntitlementDao
}

var (
	// KidsEntitlement is a globally accessible object for table kids_entitlement operations.
	KidsEntitlement = kidsEntitlementDao{internal.NewKidsEntitlementDao()}
)

// Add your custom methods and functionality below.
