// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsCircleSelectionDao is the data access object for the table kids_circle_selection.
// You can define custom methods on it to extend its functionality as needed.
type kidsCircleSelectionDao struct {
	*internal.KidsCircleSelectionDao
}

var (
	// KidsCircleSelection is a globally accessible object for table kids_circle_selection operations.
	KidsCircleSelection = kidsCircleSelectionDao{internal.NewKidsCircleSelectionDao()}
)

// Add your custom methods and functionality below.
