// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractCircleDao is the data access object for the table kids_contract_circle.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractCircleDao struct {
	*internal.KidsContractCircleDao
}

var (
	// KidsContractCircle is a globally accessible object for table kids_contract_circle operations.
	KidsContractCircle = kidsContractCircleDao{internal.NewKidsContractCircleDao()}
)

// Add your custom methods and functionality below.
