// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsRewardDefinitionDao is the data access object for the table kids_reward_definition.
// You can define custom methods on it to extend its functionality as needed.
type kidsRewardDefinitionDao struct {
	*internal.KidsRewardDefinitionDao
}

var (
	// KidsRewardDefinition is a globally accessible object for table kids_reward_definition operations.
	KidsRewardDefinition = kidsRewardDefinitionDao{internal.NewKidsRewardDefinitionDao()}
)

// Add your custom methods and functionality below.
