// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsContractTaskCancellationDao is the data access object for the table kids_contract_task_cancellation.
// You can define custom methods on it to extend its functionality as needed.
type kidsContractTaskCancellationDao struct {
	*internal.KidsContractTaskCancellationDao
}

var (
	// KidsContractTaskCancellation is a globally accessible object for table kids_contract_task_cancellation operations.
	KidsContractTaskCancellation = kidsContractTaskCancellationDao{internal.NewKidsContractTaskCancellationDao()}
)

// Add your custom methods and functionality below.
