// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsSyncCommitDao is the data access object for the table kids_sync_commit.
// You can define custom methods on it to extend its functionality as needed.
type kidsSyncCommitDao struct {
	*internal.KidsSyncCommitDao
}

var (
	// KidsSyncCommit is a globally accessible object for table kids_sync_commit operations.
	KidsSyncCommit = kidsSyncCommitDao{internal.NewKidsSyncCommitDao()}
)

// Add your custom methods and functionality below.
