// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsTaskTagDefinitionDao is the data access object for the table kids_task_tag_definition.
// You can define custom methods on it to extend its functionality as needed.
type kidsTaskTagDefinitionDao struct {
	*internal.KidsTaskTagDefinitionDao
}

var (
	// KidsTaskTagDefinition is a globally accessible object for table kids_task_tag_definition operations.
	KidsTaskTagDefinition = kidsTaskTagDefinitionDao{internal.NewKidsTaskTagDefinitionDao()}
)

// Add your custom methods and functionality below.
