// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"rslytics-app-api/internal/model/kids/dao/internal"
)

// kidsUploadFileDao is the data access object for the table kids_upload_file.
// You can define custom methods on it to extend its functionality as needed.
type kidsUploadFileDao struct {
	*internal.KidsUploadFileDao
}

var (
	// KidsUploadFile is a globally accessible object for table kids_upload_file operations.
	KidsUploadFile = kidsUploadFileDao{internal.NewKidsUploadFileDao()}
)

// Add your custom methods and functionality below.
