server:
  address: ":18002"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "debug"
  stdout: true

app:
  name: "kids"
  env: "test"

database:
  default:
    link: "mysql:root:password@tcp(127.0.0.1:3306)/rslytics_kids_test?loc=Local&parseTime=true"
    debug: true

auth:
  jwt:
    secret: "rslytics-kids-jwt-secret"
  google:
    clientId: "745375182989-oh5700da76bcq8qukis91n3jghcta68s.apps.googleusercontent.com"
  apple:
    clientId: ""
    teamId: ""
    keyId: ""
    privateKey: ""

